---
# - hosts: website
#   become: yes
#   become_user: root
#   become_method: sudo
#   roles:
#     - website

- hosts: prometheus
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: grafana
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana