#!/bin/bash
# echo "StrictHostKeyChecking=accept-new" >> /home/ec2-user/.ssh/config
# chown -R ec2-user:ec2-user ~/.ssh
# chmod 600 ~/.ssh/config
sudo yum update -y
sudo yum install ansible -y
sudo hostnamectl set-hostname controller
chmod 600 /home/ec2-user/id_rsa
chown -R ec2-user:ec2-user /home/ec2-user/id_rsa